name: Publish in DockerHub

on:
  push:
    branches: ["main", "elineef"]
    paths:
      - 'src/**'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run tests
        run: mvn test

      - name: Extraer versión del POM
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT//')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      
      - name: Build Docker image
        run: |
          mvn spring-boot:build-image -DskipTests \
            -Dspring-boot.build-image.imageName=${{ secrets.DOCKERHUB_USERNAME }}/posts:${{ steps.version.outputs.version }}

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push with verification
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/posts:${{ steps.version.outputs.version }}  # ← Usa la versión del POM
          echo "Imagen subida: ${{ secrets.DOCKERHUB_USERNAME }}/posts:${{ steps.version.outputs.version }}"