name: Publish in DockerHub

on:
  push:
    branches: ["main", "elineef"]
    paths:
      - 'src/**'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run tests
        run: mvn test

      - name: Build Docker image
        run: |
          mvn spring-boot:build-image -DskipTests \
            -Dspring-boot.build-image.imageName=${{ secrets.DOCKERHUB_USERNAME }}/posts:v1
          docker images | grep "posts" || echo "¡Error al construir la imagen!"

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push with verification
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/posts:v1
          echo "Verifica en: https://hub.docker.com/r/${{ secrets.DOCKERHUB_USERNAME }}/posts/tags"